version: '3.9'

services:
  swagger:
    image: golang:1.24-bullseye
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "sh", "-c" ]
    command: |
      go install github.com/swaggo/swag/cmd/swag@latest && \
      swag init -g cmd/api/api.go --output docs

  timescaledb:
    image: timescale/timescaledb:2.13.0-pg14
    container_name: gold-digger-timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  app:
    restart: on-failure
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOCAL_DB_HOST=timescaledb
      - LOCAL_DB_PORT=5432
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
      - LOCAL_DB_SSL=${LOCAL_DB_SSL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
      - FORCE_POLL=${FORCE_POLL}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - ALPHA_VANTAGE_API_KEY_BACKUP=${ALPHA_VANTAGE_API_KEY_BACKUP}
      - ALPHA_VANTAGE_BASE_URL=${ALPHA_VANTAGE_BASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    command: [ "./gold-digger" ]
    ports:
      - "8080:8080"
    depends_on:
      - timescaledb
    links:
      - timescaledb

volumes:
  timescaledb_data: